export default {
  "login": "srinath1",
  "id": 6961770,
  "node_id": "MDQ6VXNlcjY5NjE3NzA=",
  "avatar_url": "https://avatars.githubusercontent.com/u/6961770?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/srinath1",
  "html_url": "https://github.com/srinath1",
  "followers_url": "https://api.github.com/users/srinath1/followers",
  "following_url": "https://api.github.com/users/srinath1/following{/other_user}",
  "gists_url": "https://api.github.com/users/srinath1/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/srinath1/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/srinath1/subscriptions",
  "organizations_url": "https://api.github.com/users/srinath1/orgs",
  "repos_url": "https://api.github.com/users/srinath1/repos",
  "events_url": "https://api.github.com/users/srinath1/events{/privacy}",
  "received_events_url": "https://api.github.com/users/srinath1/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Srinath N.S",
  "company": "Eurest canteen",
  "blog": "",
  "location": "Copenhagen",
  "email": null,
  "hireable": null,
  "bio": "React, Node.js 10.x.x, React Native, Express.js 4.x.x,Mongodb, angular.js, Graphql server 15.x.x, Next. Js, Typescript 2.x.x,JavaScript, php 5.x.z,mysql 5.x.x",
  "twitter_username": null,
  "public_repos": 37,
  "public_gists": 0,
  "followers": 4,
  "following": 0,
  "created_at": "2014-03-15T18:56:22Z",
  "updated_at": "2021-09-11T11:13:44Z"
}