export default [
  {
    "login": "Ted95153420",
    "id": 5618197,
    "node_id": "MDQ6VXNlcjU2MTgxOTc=",
    "avatar_url": "https://avatars.githubusercontent.com/u/5618197?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Ted95153420",
    "html_url": "https://github.com/Ted95153420",
    "followers_url": "https://api.github.com/users/Ted95153420/followers",
    "following_url": "https://api.github.com/users/Ted95153420/following{/other_user}",
    "gists_url": "https://api.github.com/users/Ted95153420/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Ted95153420/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Ted95153420/subscriptions",
    "organizations_url": "https://api.github.com/users/Ted95153420/orgs",
    "repos_url": "https://api.github.com/users/Ted95153420/repos",
    "events_url": "https://api.github.com/users/Ted95153420/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Ted95153420/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "jfukki",
    "id": 7016269,
    "node_id": "MDQ6VXNlcjcwMTYyNjk=",
    "avatar_url": "https://avatars.githubusercontent.com/u/7016269?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/jfukki",
    "html_url": "https://github.com/jfukki",
    "followers_url": "https://api.github.com/users/jfukki/followers",
    "following_url": "https://api.github.com/users/jfukki/following{/other_user}",
    "gists_url": "https://api.github.com/users/jfukki/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/jfukki/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/jfukki/subscriptions",
    "organizations_url": "https://api.github.com/users/jfukki/orgs",
    "repos_url": "https://api.github.com/users/jfukki/repos",
    "events_url": "https://api.github.com/users/jfukki/events{/privacy}",
    "received_events_url": "https://api.github.com/users/jfukki/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "SteveWooding",
    "id": 7372191,
    "node_id": "MDQ6VXNlcjczNzIxOTE=",
    "avatar_url": "https://avatars.githubusercontent.com/u/7372191?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/SteveWooding",
    "html_url": "https://github.com/SteveWooding",
    "followers_url": "https://api.github.com/users/SteveWooding/followers",
    "following_url": "https://api.github.com/users/SteveWooding/following{/other_user}",
    "gists_url": "https://api.github.com/users/SteveWooding/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/SteveWooding/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/SteveWooding/subscriptions",
    "organizations_url": "https://api.github.com/users/SteveWooding/orgs",
    "repos_url": "https://api.github.com/users/SteveWooding/repos",
    "events_url": "https://api.github.com/users/SteveWooding/events{/privacy}",
    "received_events_url": "https://api.github.com/users/SteveWooding/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "phughesmcr",
    "id": 12073314,
    "node_id": "MDQ6VXNlcjEyMDczMzE0",
    "avatar_url": "https://avatars.githubusercontent.com/u/12073314?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/phughesmcr",
    "html_url": "https://github.com/phughesmcr",
    "followers_url": "https://api.github.com/users/phughesmcr/followers",
    "following_url": "https://api.github.com/users/phughesmcr/following{/other_user}",
    "gists_url": "https://api.github.com/users/phughesmcr/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/phughesmcr/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/phughesmcr/subscriptions",
    "organizations_url": "https://api.github.com/users/phughesmcr/orgs",
    "repos_url": "https://api.github.com/users/phughesmcr/repos",
    "events_url": "https://api.github.com/users/phughesmcr/events{/privacy}",
    "received_events_url": "https://api.github.com/users/phughesmcr/received_events",
    "type": "User",
    "site_admin": false
  }
]

